### ISSUE TITLE
Index out of range error when using mouse to select page

### ISSUE THREAD

**Issue by xpndrobserved** [xpndrobserved/GoBrief#3]
When using the mouse to navigate, anytime the user clicks on an area **other than** the page name on the ```info``` textview object, the application crashes. Issue does not occur when using the keyboard to cycle between pages.

```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/application.go:285 +0x45
panic({0x575d20?, 0xc000018228?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
main.main.func1({0x0?, 0xc000114960?, 0xc0000f37e8?}, {0xc0000f3758?, 0x55a4a0?, 0x0?}, {0xc0000f3730?, 0x4d6f45?, 0xc000530536?})
	/home/Yammins/Documents/Programming/AvWeather/main.go:47 +0x3b
github.com/rivo/tview.(*TextView).Highlight(0xc000144000, {0x7631c0, 0x0, 0x0})
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/textview.go:671 +0x67a
github.com/rivo/tview.(*TextView).MouseHandler.func1(0x3, 0x18?, 0xc000014e90)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/textview.go:1397 +0x29d
github.com/rivo/tview.(*TextView).MouseHandler.(*Box).WrapMouseHandler.func2(0x4000?, 0x10?, 0xc000548008?)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/box.go:226 +0x58
github.com/rivo/tview.(*Flex).MouseHandler.func1(0x3, 0xc000114d80, 0xc000014e90)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/flex.go:239 +0xc3
github.com/rivo/tview.(*Flex).MouseHandler.(*Box).WrapMouseHandler.func2(0x4120?, 0x43a04e?, 0x1?)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/box.go:226 +0x58
github.com/rivo/tview.(*Application).fireMouseActions.func1(0x6500?)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/application.go:522 +0x182
github.com/rivo/tview.(*Application).fireMouseActions(0x7038a0, 0xc000114d80)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/application.go:559 +0x2cd
github.com/rivo/tview.(*Application).Run(0x7038a0)
	/home/Yammins/go/pkg/mod/github.com/rivo/tview@v0.0.0-20240307173318-e804876934a1/application.go:458 +0x59c
main.main()
	/home/Yammins/Documents/Programming/AvWeather/main.go:95 +0xb94
exit status 2

```

**Comment by xpndrobserved** [comment]
Decided to rewrite the entire system for pages.
